version: "3.6"
services:

  chess:
    image: "osvedvall/chess-server:latest"
    build:
      context:  .
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == master]
    ports:
      - "9999:9999"
    networks:
      - chess-net

networks:
  chess-net:
